// <auto-generated />
using System;
using GestorInventario.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorInventario.Backend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241224031759_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Categoria", b =>
                {
                    b.Property<int>("ID_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Categoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Categoria");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Entrada_Inventario", b =>
                {
                    b.Property<int>("ID_Entrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Entrada"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Entrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Producto")
                        .HasColumnType("int");

                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("productosIdProducto")
                        .HasColumnType("int");

                    b.Property<int>("proveedoresID_Proveedor")
                        .HasColumnType("int");

                    b.HasKey("ID_Entrada");

                    b.HasIndex("Cantidad")
                        .IsUnique();

                    b.HasIndex("productosIdProducto");

                    b.HasIndex("proveedoresID_Proveedor");

                    b.ToTable("Entrada_Inventario");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("precio_unitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("stockactual")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Proveedor", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Proveedor"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Proveedor");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Entrada_Inventario", b =>
                {
                    b.HasOne("GestorInventario.Shared.Entitis.Producto", "productos")
                        .WithMany()
                        .HasForeignKey("productosIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorInventario.Shared.Entitis.Proveedor", "proveedores")
                        .WithMany()
                        .HasForeignKey("proveedoresID_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productos");

                    b.Navigation("proveedores");
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.User", b =>
                {
                    b.HasOne("GestorInventario.Shared.Entitis.Rol", null)
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GestorInventario.Shared.Entitis.Rol", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
